#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-grgit
Version  : 3.1.1
Release  : 1
URL      : https://github.com/ajoberstar/grgit/archive/3.1.1.tar.gz
Source0  : https://github.com/ajoberstar/grgit/archive/3.1.1.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/org/ajoberstar/grgit/grgit-core/3.1.1/grgit-core-3.1.1.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/org/ajoberstar/grgit/grgit-core/3.1.1/grgit-core-3.1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-grgit-data = %{version}-%{release}
Requires: mvn-grgit-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
# grgit
[![Download](https://api.bintray.com/packages/ajoberstar/maven/grgit/images/download.svg)](https://bintray.com/ajoberstar/maven/grgit/_latestVersion)
[![CircleCI](https://circleci.com/gh/ajoberstar/grgit.svg?style=svg)](https://circleci.com/gh/ajoberstar/grgit)

%package data
Summary: data components for the mvn-grgit package.
Group: Data

%description data
data components for the mvn-grgit package.


%package license
Summary: license components for the mvn-grgit package.
Group: Default

%description license
license components for the mvn-grgit package.


%prep
%setup -q -n grgit-3.1.1

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-grgit
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-grgit/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ajoberstar/grgit/grgit-core/3.1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/ajoberstar/grgit/grgit-core/3.1.1/grgit-core-3.1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/ajoberstar/grgit/grgit-core/3.1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/ajoberstar/grgit/grgit-core/3.1.1/grgit-core-3.1.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/ajoberstar/grgit/grgit-core/3.1.1/grgit-core-3.1.1.jar
/usr/share/java/.m2/repository/org/ajoberstar/grgit/grgit-core/3.1.1/grgit-core-3.1.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-grgit/LICENSE
